In [11]:
import torch
torch.nn.Module.dump_patches = True

path = './models/stylenet_transfer_att_4_complete/FAC_BEST_checkpoint_stylenet_transfer_att_4.pth.tar'
checkpoint = torch.load(path, map_location='cpu')

In [12]:
decoder = checkpoint['decoder']
encoder = checkpoint['encoder']

In [13]:
list(decoder.B.parameters())

[Parameter containing:
 tensor([[-0.0598, -0.0583,  0.0852,  ..., -0.0466,  0.0973, -0.0174],
         [-0.0664, -0.0580, -0.0276,  ...,  0.0268,  0.0489,  0.0647],
         [-0.0612,  0.0787, -0.0081,  ...,  0.0450,  0.0392, -0.0084],
         ...,
         [ 0.1014,  0.0483,  0.1029,  ..., -0.0474, -0.0401,  0.0474],
         [ 0.0444,  0.0042,  0.0462,  ...,  0.0822,  0.0262, -0.0007],
         [-0.0093, -0.0406,  0.1424,  ...,  0.1310, -0.0088, -0.0599]],
        requires_grad=True)]

In [7]:
list(decoder.B.parameters())

[Parameter containing:
 tensor([[-0.0598, -0.0583,  0.0852,  ..., -0.0466,  0.0973, -0.0174],
         [-0.0664, -0.0580, -0.0276,  ...,  0.0268,  0.0489,  0.0647],
         [-0.0612,  0.0787, -0.0081,  ...,  0.0450,  0.0392, -0.0084],
         ...,
         [ 0.1014,  0.0483,  0.1029,  ..., -0.0474, -0.0401,  0.0474],
         [ 0.0444,  0.0042,  0.0462,  ...,  0.0822,  0.0262, -0.0007],
         [-0.0093, -0.0406,  0.1424,  ...,  0.1310, -0.0088, -0.0599]],
        requires_grad=True)]

In [8]:
list(decoder.C.parameters())

[Parameter containing:
 tensor([[ 0.0427,  0.0432,  0.0597,  ...,  0.1113,  0.0246, -0.0341],
         [ 0.0270, -0.0857,  0.0209,  ...,  0.0858, -0.0392, -0.0238],
         [-0.0351, -0.0010,  0.0072,  ...,  0.0343,  0.0189,  0.0002],
         ...,
         [ 0.0305, -0.0766, -0.0180,  ..., -0.0515,  0.0006, -0.0402],
         [ 0.0070,  0.0973,  0.0369,  ..., -0.0377, -0.0506,  0.0798],
         [ 0.0869, -0.0216, -0.0122,  ..., -0.0746,  0.0436,  0.0409]],
        requires_grad=True), Parameter containing:
 tensor([-0.0201, -0.0235,  0.0015,  ...,  0.0048, -0.0011, -0.0004],
        requires_grad=True)]

In [9]:
list(decoder.attention.parameters())

[Parameter containing:
 tensor([[ 0.0076, -0.0357, -0.0417,  ..., -0.0113,  0.0075,  0.0421],
         [-0.0391, -0.0423,  0.0423,  ..., -0.0402,  0.0337, -0.0205],
         [ 0.0250,  0.0274,  0.0356,  ...,  0.0345, -0.0212,  0.0356],
         ...,
         [ 0.0361, -0.0049,  0.0297,  ...,  0.0053,  0.0385,  0.0048],
         [-0.0315,  0.0155,  0.0345,  ..., -0.0546,  0.0273,  0.0295],
         [ 0.0488, -0.0213,  0.0271,  ..., -0.0357,  0.0115, -0.0471]],
        requires_grad=True), Parameter containing:
 tensor([-8.8870e-03, -5.6883e-03, -9.6034e-03, -7.5898e-03, -5.1193e-03,
          8.9746e-03, -3.4790e-03, -1.4647e-02,  4.3426e-03, -1.0525e-02,
         -6.1353e-03, -2.3483e-03,  4.9710e-03,  4.2337e-03, -6.3814e-03,
          7.0426e-03,  3.5878e-03,  1.6541e-03, -2.9978e-03, -3.5511e-03,
          9.6170e-04, -6.5255e-04, -6.6578e-03,  7.7950e-04,  3.2912e-03,
         -4.2796e-03,  6.4869e-03,  9.1448e-03, -2.1926e-03, -5.4286e-03,
          4.8759e-03, -2.5428e-03, -2.629